import type { ThemeBundle } from "../../types/migrate.ts";
import { pickBreakpointTiers } from "./faststore-v4.ts";

/**
 * Deterministic Tailwind v4 `@theme` token block for `faststore-next`
 * (mirrors `buildFastStoreTheme` in `faststore-v4.ts`, same extracted
 * `ThemeBundle` input, different output shape — CSS custom properties
 * inside a Tailwind `@theme` layer instead of SCSS). Unlike FastStore v4,
 * this target has no framework-mandated token names (no `@faststore/cli`,
 * no `--fs-*` contract) — the names below are a reasonable convention for
 * the agent to wire into components, not something the platform enforces.
 */
export function buildFastStoreNextTheme(theme: ThemeBundle): string {
  return buildTailwindTheme(theme, [
    "/* Brand tokens — starter generated by `parity migrate --target faststore-next`. */",
    "/* Adjust names to match whatever this template's own tailwind.css already declares */",
    "/* under @theme inline — don't introduce a second, parallel token set. */",
  ]);
}

/**
 * The Tailwind v4 `@theme` block itself. Shared with `tanstack-deco`, which is also a Tailwind
 * target — the token mapping is identical, only the header comment differs. Extracted so a new
 * Tailwind target is a header string, not a copy of this function.
 */
export function buildTailwindTheme(theme: ThemeBundle, header: string[]): string {
  const lines: string[] = [];
  const put = (token: string, value: string | null | undefined) => {
    if (value) lines.push(`  ${token}: ${value};`);
  };
  const fonts = theme.typography.fontFamilies;
  const radii = theme.radii;
  const bp = theme.breakpoints;

  put("--color-brand-primary", theme.colors.primary);
  put("--color-brand-secondary", theme.colors.secondary);
  put("--color-brand-text", theme.colors.text);
  put("--color-brand-background", theme.colors.background);
  put("--font-body", fonts[0]);
  put("--font-heading", fonts[1] ?? fonts[0]);
  put("--radius-brand", radii[Math.floor(radii.length / 2)]);
  put("--shadow-brand", theme.shadows[0]);
  const tiers = pickBreakpointTiers(bp);
  put("--breakpoint-phone", tiers.phone);
  put("--breakpoint-tablet", tiers.tablet);
  put("--breakpoint-notebook", tiers.notebook);
  put("--breakpoint-desktop", tiers.desktop);

  return [...header, "@theme {", ...lines, "}", ""].join("\n");
}

/**
 * FastStore Next target playbook. A short pointer for the migration agent —
 * bootstrap + the porting checklist + hard rules, NOT inlined docs (token
 * economy, same rationale as faststore-v4.ts). Full depth lives in the
 * `parity` plugin's `skills/target-faststore-next/SKILL.md` — load that
 * before porting the first section; this is the CLI-output-sized pointer.
 *
 * Shipped as a `.ts` string (not `.md`) so `bun build` bundles it into
 * `dist/cli.js` — loose `.md` files aren't copied to `dist`.
 */
export const faststoreNext = `## Target: FastStore Next

Next.js App Router on \`@faststore/api\`/\`sdk\`/\`ui\` — no \`@faststore/cli\`/\`core\`,
Deco CMS decofiles as the content source. This is a DIFFERENT target from
\`faststore-v4\` (which scaffolds \`@faststore/cli\` + the VTEX Headless CMS) —
don't mix their playbooks. Load \`skills/target-faststore-next/SKILL.md\` for
the full picture; this is the condensed version.

### Bootstrap
- Scaffold by copying \`deco-sites/faststore-next-template\` (clone, copy the
  tree, re-init git, set the new remote) — NOT the bare FastStore starter.
  It ships the platform layer (PLP pagination/ISR, gradual-cutover proxy,
  native Synerise+VTEX-fallback search, WebOps deploy accommodations) —
  reinventing any of those from scratch is exactly what the template exists
  to avoid.
- \`bun dev\` — localhost:3000 · \`bun run build\` — prod build (runs \`generate\`
  first) · \`bun run generate:deco\` — after adding/changing a section,
  restart dev after.
- Set \`discovery.config.js\`'s \`api.storeId\` (public, client-bundled — not a
  secret) to the source VTEX account (the \`*.vtexassets.com\` subdomain in
  \`blocks.json\`, or the account id from \`window.__RUNTIME__\` on a live
  vtex-io source).

### Styling — Tailwind v4, not SCSS
No \`--fs-*\` token contract (that's the other target). A starter
\`@theme\` block was generated in this snapshot from the extracted brand
tokens — merge it into the template's own \`src/styles/tailwind.css\`
\`@theme inline\` block rather than adding a second token layer. Token map
used: primary/secondary/text/background colors, body/heading fonts, one
mid-scale radius, first shadow, and the four nearest-canonical breakpoint
tiers (phone/tablet/notebook/desktop) picked from the extracted breakpoint
list.

### Icons
Sprite-based (\`public/sprites-v2.svg\` + the template's \`Icon\` component,
a typed union in \`icons.ts\`) — not Phosphor, not per-icon SVG files. Add
missing icons to the sprite + the union type.

### Brand assets
Logo/favicon downloaded to \`assets/\` in this snapshot — the template ships
a generic placeholder at \`public/brand/logo-placeholder.svg\`; replace it
and wire it into \`src/components/header/{Desktop,Mobile}Header.tsx\`.

### Where components go — this target's 3-point-invariant equivalent
Every section needs all three or the CMS silently drops it:
1. The component in \`src/components/sections/<Path>/<Name>.tsx\` — its typed
   \`Props\` export IS the CMS schema (no separate \`.jsonc\` to hand-write).
2. The shim in \`src/sections/<Path>.tsx\` — thin re-export,
   \`export { default } from "src/components/sections/<Path>/<Name>"\`, plus
   convention exports (\`sync\`, \`layout\`, \`cache\`, …). The file's PATH is
   the Studio block key.
3. \`bun run generate:deco\` to regenerate \`.deco/*.gen.*\`.
Global vs page-scoped: \`layout = true\` sections (Header/Footer) resolve
once and cache across navigations; everything else is page content.

### Editability gate (check every ported section)
Does it read from its decofile, or did the port hardcode the captured
content into JSX? Trivial/empty \`Props\` or literal strings >~25 chars in
the component body means a merchant can't edit it in Studio — visually
identical to prod, but a CMS regression \`parity\`'s screenshot/HTML diff
cannot see.

### Rendering — decide this BEFORE porting the first section
CMS data renders SSR; product/search data renders CSR when the site uses a
third-party search provider (its requests are shopper-session-dependent and
browser-only). This is an architecture decision made once, up front — do
not let \`parity\` flag the resulting SSR/CSR delta as a regression against
a source that server-rendered products.

### Deploy
WebOps builds straight from \`discovery.config.js\` + \`package.json\`
scripts — no CLI, no deploy workflow to create. Two accommodations that
look wrong to a generic Node reviewer but are load-bearing: build-time
tooling sits in \`dependencies\` (WebOps production installs skip
\`devDependencies\`), and branch names can't contain a second \`/\`.`;
