import type { ThemeBundle } from "../../types/migrate.ts";

/**
 * Deterministic `custom-theme.scss` for FastStore v4: maps the extracted
 * BRAND tokens to `--fs-*` global tokens inside `.theme`. Intentionally maps
 * only colors / fonts / radius / shadow / breakpoints — NOT `--fs-spacing-*`
 * or `--fs-text-size-*`, which are the design-system's structural scale
 * (overriding them to arbitrary site values breaks component layout). A
 * starter the agent refines.
 */
/**
 * Map a noisy list of breakpoint widths to phone/tablet/notebook/desktop by
 * nearest-to-canonical (480/768/1024/1280px), without reusing a width. The
 * 4-smallest naive pick returns mobile-cluster noise (320/340/…); this picks
 * the meaningful tiers. Pure — unit-tested.
 */
export function pickBreakpointTiers(breakpoints: string[]): {
  phone: string | null;
  tablet: string | null;
  notebook: string | null;
  desktop: string | null;
} {
  const px = breakpoints
    .map((b) => ({ raw: b, n: Number.parseFloat(b) }))
    .filter((b) => Number.isFinite(b.n));
  const used = new Set<string>();
  const nearest = (target: number): string | null => {
    let best: { raw: string; d: number } | null = null;
    for (const b of px) {
      if (used.has(b.raw)) continue;
      const d = Math.abs(b.n - target);
      if (!best || d < best.d) best = { raw: b.raw, d };
    }
    if (best) used.add(best.raw);
    return best?.raw ?? null;
  };
  return {
    phone: nearest(480),
    tablet: nearest(768),
    notebook: nearest(1024),
    desktop: nearest(1280),
  };
}

export function buildFastStoreTheme(theme: ThemeBundle): string {
  const lines: string[] = [];
  const put = (token: string, value: string | null | undefined) => {
    if (value) lines.push(`  ${token}: ${value};`);
  };
  const fonts = theme.typography.fontFamilies;
  const radii = theme.radii;
  const bp = theme.breakpoints;

  put("--fs-color-primary-bkg", theme.colors.primary);
  put("--fs-color-accent-0", theme.colors.secondary);
  put("--fs-color-text", theme.colors.text);
  put("--fs-color-body-bkg", theme.colors.background);
  put("--fs-text-face-body", fonts[0]);
  put("--fs-text-face-title", fonts[1] ?? fonts[0]);
  put("--fs-border-radius-medium", radii[Math.floor(radii.length / 2)]);
  put("--fs-shadow", theme.shadows[0]);
  const tiers = pickBreakpointTiers(bp);
  put("--fs-grid-breakpoint-phone", tiers.phone);
  put("--fs-grid-breakpoint-tablet", tiers.tablet);
  put("--fs-grid-breakpoint-notebook", tiers.notebook);
  put("--fs-grid-breakpoint-desktop", tiers.desktop);

  return [
    "// custom-theme.scss — starter generated by `parity migrate --target faststore`.",
    "// Brand tokens only; adjust and extend against @faststore/ui global tokens.",
    ".theme {",
    ...lines,
    "}",
    "",
  ].join("\n");
}

/**
 * FastStore (VTEX) v4 target playbook. A short pointer for the migration agent
 * — CLI commands + doc URLs + structure map, NOT inlined docs (token economy).
 * The agent scaffolds with `@faststore/cli` and fills sections; there is no
 * codegen exporter in the core (see plan).
 *
 * Shipped as a `.ts` string (not `.md`) so `bun build` bundles it into
 * `dist/cli.js` — loose `.md` files aren't copied to `dist`.
 */
export const faststore = `## Target: VTEX FastStore (v4)

Generate the migrated storefront as a FastStore v4 project. Do NOT hand-roll the
scaffold — use the official CLI, then fill in sections from the components below.

### Setup (once)
- Requirements + project setup: https://developers.vtex.com/docs/guides/faststore/getting-started-requirements
- Project structure overview: https://developers.vtex.com/docs/guides/faststore/project-structure-overview
- \`yarn install\` then \`yarn dev\` → dev store at http://localhost:3000

### CLI (@faststore/cli)
- \`faststore dev\` — local dev server (localhost:3000)
- \`faststore build\` — production build
- \`faststore generate\` — regenerate schema + TS types after changes
- \`faststore cms-sync\` — sync the \`cms/\` folder with the Headless CMS

### Styling — IMPORTANT: FastStore does NOT use Tailwind
FastStore v4 styles with **SCSS design tokens + \`data-fs-*\` attributes**, not
utility classes. The Tailwind classes in each component README are a convenience
approximation — treat the **raw computed styles in manifest.json as the source
of truth** for exact values. Package split: \`@faststore/components\` (structure/
behavior, unstyled) · \`@faststore/ui\` (styles + design tokens) · \`@faststore/core\`
(sections/pages).

- **Theme** → a starter \`custom-theme.scss\` was generated in this snapshot from
  the extracted brand tokens. Drop it in \`src/themes/\` and refine. Token map used:

  | Extracted | FastStore global token |
  | --- | --- |
  | primary | \`--fs-color-primary-bkg\` |
  | secondary | \`--fs-color-accent-0\` |
  | text | \`--fs-color-text\` |
  | background | \`--fs-color-body-bkg\` |
  | font (body/title) | \`--fs-text-face-body\` / \`--fs-text-face-title\` |
  | radius | \`--fs-border-radius-medium\` |
  | shadow | \`--fs-shadow\` |
  | breakpoints | \`--fs-grid-breakpoint-phone|tablet|notebook|desktop\` |

  Do NOT override \`--fs-spacing-*\`/\`--fs-text-size-*\` (structural scale).
  Global tokens: https://developers.vtex.com/docs/guides/faststore/global-tokens-overview
- **Per-component styling** → override via each component's \`data-fs-*\` attribute
  in SCSS (e.g. \`[data-fs-product-shelf]\`), not utility classes.
  Styling a component: https://developers.vtex.com/docs/guides/faststore/using-themes-components

### Icons — Phosphor
FastStore ships Phosphor icons via the \`<Icon>\` component (\`data-fs-icon\`, \`weight\`
prop: thin|light|regular|bold). Map each entry in this snapshot's **icon inventory**
to a Phosphor icon id; add any missing ones as custom icons.
- Iconography: https://developers.vtex.com/docs/guides/faststore/reference-icons
- Adding custom icons: https://developers.vtex.com/docs/guides/faststore/atoms-icon

### Brand assets
- Logo + favicon (and apple-touch-icon / OG image) were downloaded to \`assets/\`
  in this snapshot — drop them into the FastStore project's \`public/\` and wire the
  logo into the Navbar/Header section.

### Where components go — section structure
Each detected component → a FastStore section:
- \`src/components/<SectionName>.tsx\` (the React section)
- register it in \`src/components/index.tsx\` (the components entry)
- add its schema to \`cms/faststore/sections.json\` (form editors use in the CMS)
- **Global components** (header/footer/minicart) render on every page;
  **page components** (home/PLP/PDP) go into the matching page content type.
- After adding/editing sections: \`faststore generate\` then \`faststore cms-sync\`.
- Splitting a legacy CMS structure into components/content-types is supported by
  \`vtex content split-components\` and \`vtex content split-content-types\`.
- Creating a section: https://developers.vtex.com/docs/guides/faststore/building-sections-creating-a-new-section
- Headless CMS model: https://developers.vtex.com/docs/guides/faststore/headless-cms-overview
- Creating sections: https://developers.vtex.com/docs/guides/faststore/creating-a-new-section-and-content-type

### e2e
Use the suggested selectors (per component, mapped to known commerce keys) to
seed Playwright/Cypress smoke tests on the migrated store.`;
